### PR TITLE
FIX Use get_one_by_stage when fetching SiteTree for a specific stage

### LINKED ISSUE #51: Versioned::use_session Fallback breaks page editing
The `use_session` fallback introduced in SilverStripe 4.2 is intended to maintain the existing behaviour of the framework / CMS, by storing the stage in the session as before.

When this fallback is enabled and `silverstripe-versioned-admin` is installed (as a dependency of `silverstripe-elemental` in my case), attempting to open a page for editing in the CMS results in the following error:

```
[Emergency] Uncaught InvalidArgumentException: Invalid stage name ""
GET /admin/pages/edit/show/9018
Line 160 in /var/www/mysite/www/vendor/silverstripe/versioned/src/ReadingMode.php

Source
151 
152     /**
153      * Validate the stage is valid, throwing an exception if it's not
154      *
155      * @param string $stage
156      */
157     public static function validateStage($stage)
158     {
159         if (!in_array($stage, [Versioned::LIVE, Versioned::DRAFT])) {
160             throw new InvalidArgumentException("Invalid stage name \"{$stage}\"");
161         }
162     }
163 }
Trace
SilverStripe\Versioned\ReadingMode::validateStage() 
Versioned.php:2148
SilverStripe\Versioned\Versioned::set_stage() 
HistoryControllerFactory.php:35
SilverStripe\VersionedAdmin\Controllers\HistoryControllerFactory->create(SilverStripe\CMS\Controllers\CMSPageHistoryController, Array) 
Injector.php:585
SilverStripe\Core\Injector\Injector->instantiate(Array, SilverStripe\CMS\Controllers\CMSPageHistoryController, singleton) 
Injector.php:993
SilverStripe\Core\Injector\Injector->getNamedService(SilverStripe\CMS\Controllers\CMSPageHistoryController, 1, Array) 
Injector.php:946
SilverStripe\Core\Injector\Injector->get(SilverStripe\CMS\Controllers\CMSPageHistoryController) 
LeftAndMain.php:290
SilverStripe\Admin\LeftAndMain->getCombinedClientConfig() 
LeftAndMain.php:673
SilverStripe\Admin\LeftAndMain->init() 
CMSMain.php:179
...
```

This issue can be temporarily alleviated by appending the stage to the URL (e.g. `?stage=Stage`).

A somewhat similar issue with the `asset-admin` module has been raised [here](https://github.com/silverstripe/silverstripe-admin/issues/607).

### PR DESCRIPTION
**Pull request by ScopeyNZ**
I had trouble reproducing this using the steps that @Cheddam provided but I managed to reproduce it consistently with a test (that I've added to this commit). Yay for TDD!

Resolves #51

### CODE REVIEW

File: tests/Controllers/HistoryControllerFactoryTest/HistoryControllerFactoryExtension.php [hunk 1]
```diff
@@ -0,0 +1,14 @@
+<?php
+namespace SilverStripe\AssetAdmin\Tests\Controller\HistoryControllerFactory;
```
Comment (robbieaverill) [inline tests/Controllers/HistoryControllerFactoryTest/HistoryControllerFactoryExtension.php]: The package name is wrong

File: tests/Controllers/HistoryControllerFactoryTest/HistoryControllerFactoryExtension.php [hunk 2]
```diff
@@ -0,0 +1,14 @@
...
+
+use SilverStripe\Core\Extension;
+use SilverStripe\Dev\TestOnly;
+
+class HistoryControllerFactoryExtension extends Extension implements TestOnly
+{
+    public function updateIsEnabled($record)
+    {
+        return $record->Title === '2';
```
Comment (robbieaverill) [inline tests/Controllers/HistoryControllerFactoryTest/HistoryControllerFactoryExtension.php]: Can you add a comment that this is referring to HistoryControllerFactoryTest.yml fixtures?

File: tests/Controllers/HistoryControllerFactoryTest/HistoryControllerFactoryExtension.php (hunk 1 above)
Comment (ScopeyNZ) [reply tests/Controllers/HistoryControllerFactoryTest/HistoryControllerFactoryExtension.php]: 🤦‍♂️
